### ISSUE TITLE
valac: `TextViewLayer' could not be found

### ISSUE THREAD

**Issue by TSlivede** [RedHatter/finalterm-reborn#12]
I like the Idea of finalterm very much, so thanks for working on it!

However, when I try to build it, valac can't find the type "TextViewLayer".

I installed the requirements as listed in readme.md:
`sudo apt-get install intltool cmake make valac libgtk-3-dev libkeybinder-3.0-dev libgee-0.8-dev libjson-glib-dev libunity-dev libnotify-dev`

After cloning the ropo and creating build folder, `cmake` worked fine.

> user@PC:`path`/finalterm-reborn/build$ cmake ..
> -- The C compiler identification is GNU 4.8.4
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
> -- checking for module 'unity'
> --   found unity, version 7.1.4
> -- checking for module 'libnotify'
> --   found libnotify, version 0.7.6
> -- checking for modules 'gtk+-3.0;keybinder-3.0;gee-0.8;json-glib-1.0;unity;libnotify'
> --   found gtk+-3.0, version 3.10.8
> --   found keybinder-3.0, version 0.3.0
> --   found gee-0.8, version 0.10.5
> --   found json-glib-1.0, version 0.16.2
> --   found unity, version 7.1.4
> --   found libnotify, version 0.7.6
> -- Found Vala: /usr/bin/valac
> -- checking for a minimum Vala version of 0.16.0
> --   found Vala, version 0.22.1
> -- Found Gettext: /usr/bin/xgettext (found version "0.18.3") 
> -- Found Intltool: /usr/bin/intltool-extract (found version "0.50.2") 
> -- GSettings schemas will be installed locally.
> -- GSettings shemas will be compiled.
> -- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
> -- Configuring done
> -- Generating done
> -- Build files have been written to: `path`/finalterm-reborn/build`

Running `make` after that fails:

> user@PC:`path`/finalterm-reborn/build$ make
> [  3%] Generating src/FinalTerm.c, src/Terminal.c, src/TerminalStream.c, src/Encoder.c, src/TerminalOutput.c, src/CharacterAttributes.c, src/TerminalView.c, src/TextView.c, src/TerminalWidget.c, src/NestingContainer.c, src/Autocompletion.c, src/NotifyingList.c, src/ScrollableTreeView.c, src/Utilities.c, src/SettingsWindow.c, src/TextMenu.c, src/ColorScheme.c, src/Theme.c, src/KeyBindings.c, src/Command.c, src/Settings.c, src/Metrics.c, src/StatusBar.c
> `path`/finalterm-reborn/src/Encoder.vala:395.7-395.18: warning: chained relational expressions are experimental
>         if (95 < d < 127) return dec_special[d - 96];
>             ^^^^^^^^^^^^
> `path`/finalterm-reborn/src/TextView.vala:38.35-38.47: error: The type name `TextViewLayer' could not be found
>     public override void draw_layer (TextViewLayer layer, Cairo.Context cr) {
>                                      ^^^^^^^^^^^^^
> Compilation failed: 1 error(s), 1 warning(s)
> make[2]: **\* [vala.stamp] Fehler 1
> make[1]: **\* [CMakeFiles/finalterm.dir/all] Fehler 2
> make: **\* [all] Fehler 2

Do I need to install additional requirements?

PS: I'm on `Ubuntu 14.04.5 LTS`

**Comment by RedHatter** [comment]
It seems a recent change I made pushed the valac dependence to version 0.25.1, you have 0.22.1. I believe I should be able to change the code to support earlier versions. I'll look into it later today.

**Comment by TSlivede** [comment]
Just tested, it works on `Ubuntu 16.04.1 LTS`

Thank you very much!!
